#!/usr/bin/env bash
# strip_trailers.sh — assert that a commit's message contains NO co-author /
# AI-attribution trailers. If any are found, amend the commit to remove them.
#
# Usage: bash strip_trailers.sh [<commit-ish>]
#        (default: HEAD)
#
# Patterns flagged:
#   - Co-Authored-By:
#   - Co-Authored:
#   - Co-Author:
#   - Signed-off-by: Claude
#   - 🤖 Generated with
#   - Generated by Claude
#   - Generated with [Claude
#
# Exit codes:
#   0 = clean (no trailers found, or amend succeeded)
#   1 = found trailers but could not amend (working tree dirty, etc.)

set -euo pipefail

COMMIT="${1:-HEAD}"

MSG=$(git log -1 --format=%B "$COMMIT")

PATTERNS=(
  '^Co-Authored-By:'
  '^Co-Authored:'
  '^Co-Author:'
  '^Signed-off-by:.*[Cc]laude'
  '🤖 Generated with'
  '[Gg]enerated by [Cc]laude'
  '[Gg]enerated with \[?[Cc]laude'
)

found=0
for p in "${PATTERNS[@]}"; do
  if echo "$MSG" | grep -qE "$p"; then
    found=1
    break
  fi
done

if [[ $found -eq 0 ]]; then
  exit 0
fi

# Strip the offending lines and amend.
CLEAN=$(echo "$MSG" | grep -vE "$(IFS='|'; echo "${PATTERNS[*]}")" || true)

# Trim trailing blank lines that may be left behind.
CLEAN=$(printf '%s\n' "$CLEAN" | awk 'NF{p=1} p{print}' | awk 'BEGIN{RS=""; ORS="\n\n"} {print}' | sed -e 's/[[:space:]]*$//')

if [[ -z "$CLEAN" ]]; then
  echo "strip_trailers.sh: stripping would leave an empty message; refusing." >&2
  exit 1
fi

# Only amend if we're targeting HEAD — never rewrite older commits silently.
if [[ "$COMMIT" != "HEAD" ]]; then
  echo "strip_trailers.sh: trailers found in $COMMIT but not amending (not HEAD)." >&2
  echo "Manually fix with: git rebase -i $COMMIT^" >&2
  exit 1
fi

git commit --amend -m "$CLEAN" --no-verify >/dev/null
echo "strip_trailers.sh: trailers removed from HEAD."
exit 0
