#!/usr/bin/env bash
# strip_trailers.sh
# Strips Co-Authored-By and other trailers from a commit message.

TARGET="$1"

if [ -z "$TARGET" ]; then
  echo "Usage: $0 <commit-msg-file-or-HEAD>" >&2
  exit 1
fi

if [ "$TARGET" = "HEAD" ]; then
  # We need to amend the current HEAD
  MSG=$(git log -1 --format=%B | grep -v -i "^Co-Authored-By:" | grep -v -i "^Signed-off-by:" | grep -v -i "^Generated with" | grep -v -i "^Generated by Claude")
  git commit --amend -m "$MSG"
else
  # It's a file
  if [ -f "$TARGET" ]; then
    grep -v -i "^Co-Authored-By:" "$TARGET" | grep -v -i "^Signed-off-by:" | grep -v -i "^Generated with" | grep -v -i "^Generated by Claude" > "${TARGET}.tmp"
    mv "${TARGET}.tmp" "$TARGET"
  fi
fi
